### ISSUE TITLE
Why aren't the positional embeddings used during inference?

### ISSUE THREAD

**Issue by seanswyi** [pmixer/SASRec.pytorch#32]
Hi. I just had another question regarding the implementation. I'm not sure if you'd be able to answer or not but I observed that the positional embeddings aren't being used for inference (inside the model's `predict` method).

Why is this? In my own implementation I made a separate `EmbeddingLayer` module that passes input sequences through an item embedding matrix and adds positional embeddings as well in one go (as is also implied in the official paper's figure).

Is there some sort of reason why it's done this way, or is this just some arbitrary choice by the original authors?

**Comment by pmixer** [comment]
@seanswyi Hi Sean, personally, I believe positional embedding got used both in training and prediction(though I am always wondering whether there would be better approach for using positional embeddings than current one).

You may have been confused on pos_emb and pos_embs, sorry for the misleading variable names.

positional embedding got used in log2feats https://github.com/pmixer/SASRec.pytorch/blob/master/model.py#L69 for both training and inference https://github.com/pmixer/SASRec.pytorch/blob/master/model.py#L97 , https://github.com/pmixer/SASRec.pytorch/blob/master/model.py#L111

`pos` in `pos_embs` actually means positive here https://github.com/pmixer/SASRec.pytorch/blob/master/model.py#L99

**Comment by seanswyi** [comment]
Ah yes, I should have read a little more thoroughly. Thanks for clearing things up!
