### ISSUE TITLE
关于evaluate中test[u][0]的问题

### ISSUE THREAD

**Issue by shadowfall09** [pmixer/SASRec.pytorch#43]
在实现中，item_idx = [test[u][0]]，这里将test[u][0]放在了第一个，然后再随机挑选100个加入item_idx，这样inference可以得到和readme中近似的结果；但是我如果将test[u][0]放在item_idx最后一个（在100个随机之后加入），会得到很低的分数(NDCG@10: 0.0405, HR@10: 0.0950)，按道理item_idx的顺序应该没有影响，麻烦解答一下

**Comment by pmixer** [comment]
@shadowfall09 因为是实验代码，需要设到第一位才能正常工作。
如果想做些其它尝试时候变更了相关代码又要保持正确性，需要把双 argsort 从 score 到 rank 的操作也一并修改https://pmixer.github.io/posts/Argsort，或者直接采用你自己喜欢的方式去实现从打分值到排序位次的计算过程。

**Comment by shadowfall09** [comment]
明白了，感谢您的解答
